name: Report Bug
description: Report a problem or behavior that is different from what is expected.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please check the existing `ISSUES` to ensure you are not reporting a duplicate problem. If you find a similar issue, feel free to contribute with additional information if necessary.
  - type: textarea
    attributes:
      label: Description
      description: What kind of problem did you encounter? Please describe it clearly and add images if applicable.
      placeholder: |
        I encountered a problem on the page ... when I was trying to...
        The result was this:
        ![image](https://example.com/image)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce the Problem
      description: What are the steps someone needs to follow to reproduce the issue?
      placeholder: |
        1. As a logged-in user, go to the page...
        2. Click on...
        3. Do...
        4. Return to ... and observe the error.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Browsers Tested
      description: In which browsers did you notice this issue?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
        - Other
  - type: textarea
    attributes:
      label: Possible Solution
      description: Have you thought of something that could solve this problem? If so, share it below.
      placeholder: |
        Instead of ... we could change ... to...
        Here's an example of how it could look:
        ![image](https://example.com/image)
