name: Suggest a New Feature
description: Suggest a new feature, functionality, or improvement.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please check the existing `ISSUES` to ensure you are not suggesting something that already exists. If you find a similar issue, feel free to contribute with additional information if necessary.
  - type: textarea
    attributes:
      label: Description
      description: What would you like to improve? Please describe your suggestion and the need you currently have that this suggestion would solve.
      placeholder: |
        I think the page ... would be better if ... because I had difficulty with...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation Suggestion
      description: Have you thought about how this could be implemented? Share images, code, or references that you think would be useful for implementing this suggestion.
      placeholder: |
        We could change ... to add ... I made some sketches of how this could look:
        ![image](https://example.com/image)
